services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:${DOCKER_PORT}"
    environment:
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR_PATH}:/kavita/config
      - ${MANGA_DIR_PATH}:/manga:ro
      - ${LN_DIR_PATH}:/lns:ro
      - ${SOFTLINK_COMPAT_PATH}:${SOFTLINK_COMPAT_PATH}:ro # path for soft-linked files
