services:
  wireguard2:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard2
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR_PATH}:/config
      - ${LIB_MODULES}:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "${WEBUI_PORT}:${DOCKER_UI_PORT}"        # qBittorrent WebUI
      - "${TORRENTING_PORT}:${TORRENTING_DOCKER_PORT}/tcp"    # torrent port
      - "${UDP_PORT}:${UDP_DOCKER_PORT}/udp"    # torrent port (DHT/peer traffic)
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:wireguard2"
    depends_on:
      - wireguard2
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${WEBUI_PORT}
      - TORRENTING_PORT=${TORRENTING_PORT}
    volumes:
      - ${QBIT_CONFIG_DIR}:/config
      - ${QBIT_CONFIG_DOWNLOADS}:/downloads
    restart: unless-stopped
