name: navidrome
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:${DOCKER_PORT}"
    environment:
      ND_SCANSCHEDULE: ${ND_SCANSCHEDULE}
      ND_LOGLEVEL: ${ND_LOGLEVEL}
      ND_SESSIONTIMEOUT: ${ND_SESSIONTIMEOUT}
      ND_AGENTS: ${AGENTS}
      ND_LASTFM_APIKEY: ${ND_LASTFM_APIKEY}
      ND_LASTFM_SECRET: ${ND_LASTFM_SECRET}
      ND_LYRICSPRIORITY: ${ND_LYRICSPRIORITY}
    volumes:
      - "${DATA_DIR_PATH}:/data"
      - "${MUSIC_DIR_PATH}:/music:ro"
