name: nextcloud
services:
  db:
    image: mariadb:10.6
    container_name: nextcloud_db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ${MYSQL_DB_PATH}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: ${MYSQL_USER} 

  app:
    image: nextcloud:latest
    container_name: nextcloud_app
    restart: unless-stopped
    ports:
      - "${APP_HOST_PORT}:${APP_DOCKER_PORT}"
    links:
      - db
    volumes:
      - ${HTML_DIR_PATH}:/var/www/html
      - ${KAVITA_DIR_PATH}:/mnt/manga # kavita external storage link
      - ${TORRENT_DIR_PATH}:/mnt/torrents # qbittorrent external storage link
      - ${VN_DIR_PATH}:/mnt/backup/vns # vn external storage link
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_HOST: ${MYSQL_HOST}
    depends_on:
      - ${MYSQL_HOST}
