name: nextcloud
services:
  db:
    image: mariadb:10.6
    container_name: nextcloud_db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: ${MYSQL_USER} 

  app:
    image: nextcloud:latest
    container_name: nextcloud_app
    restart: unless-stopped
    ports:
      - "8080:80"
    links:
      - db
    volumes:
      - ./data:/var/www/html
      - /home/nyarlathotep/media/manga:/mnt/manga # kavita external storage link
      - /home/nyarlathotep/downloads/torrents/:/mnt/torrents # qbittorrent external storage link
      - /home/nyarlathotep/backup/vns/:/mnt/backup/vns # vn external storage link
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_HOST: ${MYSQL_HOST}
    depends_on:
      - ${MYSQL_HOST}
