services:
  collabora:
    image: collabora/code
    container_name: collabora
    restart: unless-stopped
    cap_add:
      - MKNOD
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    ports:
      - "${HOST_PORT}:${DOCKER_PORT}"
    environment:
      - domain=${DOMAIN}
      - username=${USERNAME}
      - password=${PASSWORD}
      - extra_params=${EXTRA_PARAMS}
