services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: always
    ports:
      - "${HOST_PORT}:${DOCKER_PORT}"  
    volumes:
      - ${DATA_DIR_PATH}:/app/data
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${DOCKER_PORT}"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
