name: tududi
services:
  tududi:
    image: 'chrisvel/tududi:latest'
    ports:
      - "${PORT}:3002"
    volumes:
      - ${DB_DIR}:/app/db
      - ${UPLOAD_DIR}:/app/uploads
    environment:
      - TUDUDI_USER_EMAIL=${EMAIL}
      - TUDUDI_USER_PASSWORD=${PASSWD}
      - TUDUDI_SESSION_SECRET=${SECRET}
      - TUDUDI_ALLOWED_ORIGIN=${ALLOWED_URL}:${PORT}
      - TUDUDI_TRUST_PROXY=${TRUST_PROXY}
      - CALDAV_ENABLED=${CALDAV_ENABLED}
      - ENCRYPTION_KEY=$(openssl rand -hex 32)
      - PUID=${PUID}
      - GUID=${GUID}
